"""
LangGraph AgentState definition.

The AgentState TypedDict is the single shared data structure
passed between all nodes in the LangGraph workflow. Every node
reads from and writes to this state dict.

Design principles:
- All fields are Optional so nodes only populate what they produce.
- DataFrames are stored as pandas DataFrames (not serialized) because
  the workflow runs in-process within a single Streamlit session.
- Tool outputs use the typed Pydantic models defined in models/.
"""

from __future__ import annotations

from typing import Any, Optional, TypedDict

import pandas as pd

from models.analysis_models import (
    AnomalyReport,
    AnalysisResult,
    BusinessInsight,
    DataProfile,
    IntentClassification,
    PandasGenerationResult,
    QueryResult,
    ReasoningTrace,
    SQLGenerationResult,
)
from models.chart_models import ChartResult
from models.session_models import SessionState


class AgentState(TypedDict, total=False):
    """
    Shared state flowing through the LangGraph workflow.

    Each field corresponds to the output of a specific node or tool.
    Nodes declare which fields they read and write in their docstrings.
    """

    # ── Input ──────────────────────────────────────────────────────────────────
    question: str
    """The user's natural language question."""

    dataframe: Optional[pd.DataFrame]
    """The active DataFrame to analyze. Populated before graph invocation."""

    table_name: str
    """SQLite table name for the active dataset."""

    dataset_name: str
    """Display name of the active dataset."""

    session: Optional[SessionState]
    """Full session state for memory access."""

    # ── Planner outputs ────────────────────────────────────────────────────────
    intent: Optional[IntentClassification]
    """Intent classified by the planner node."""

    # ── Tool outputs ───────────────────────────────────────────────────────────
    query_result: Optional[QueryResult]
    """Result from the query engine."""

    sql_result: Optional[SQLGenerationResult]
    """Result from the SQL generator."""

    pandas_result: Optional[PandasGenerationResult]
    """Result from the Pandas code generator."""

    chart_results: list[ChartResult]
    """Charts generated by the visualizer."""

    anomaly_report: Optional[AnomalyReport]
    """Anomaly detection report."""

    business_insights: list[BusinessInsight]
    """Business insights generated."""

    data_profile: Optional[DataProfile]
    """Dataset profile (populated on upload, not per-query)."""

    # ── Reasoning ─────────────────────────────────────────────────────────────
    reasoning_trace: Optional[ReasoningTrace]
    """Explainability trace built by the reasoning engine."""

    # ── Final output ──────────────────────────────────────────────────────────
    final_answer: str
    """The synthesized natural language response to return to the user."""

    analysis_result: Optional[AnalysisResult]
    """Complete structured result returned to the UI layer."""

    # ── Control flow ──────────────────────────────────────────────────────────
    error: Optional[str]
    """Error message if a node fails."""

    tool_execution_times: dict[str, float]
    """Per-tool execution times in milliseconds for the reasoning trace."""
